# Generated by Django 4.1.7 on 2023-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
