# Generated by Django 4.1.7 on 2023-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_record_data_alter_record_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="data",
            new_name="exercisedata",
        ),
    ]
