# Generated by Django 4.1.7 on 2023-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_data_record_exercisedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='healthdata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
