# Generated by Django 4.1.7 on 2023-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_exercisedata_record_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dataType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
