# Generated by Django 4.1.7 on 2023-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_customer_avator_recorddp"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
