# Generated by Django 4.1.7 on 2023-08-05 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_recorddp_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="data",
        ),
        migrations.RemoveField(
            model_name="recorddp",
            name="data",
        ),
    ]
