# Generated by Django 4.1.7 on 2023-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_record_data_remove_recorddp_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="netid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
