# Generated by Django 4.2.3 on 2023-08-27 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0014_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="file",
            field=models.FileField(upload_to="logs"),
        ),
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
