# Generated by Django 4.2.3 on 2023-08-29 14:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_log_file_alter_log_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="recorddp",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="file",
            field=models.FileField(upload_to=api.models.Log.filename),
        ),
    ]
