# Generated by Django 4.2.3 on 2023-11-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_customer_faculty_customer_male_customer_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
