# Generated by Django 4.2.3 on 2023-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_customer_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
