on:
  push:
    paths:
      - '.github/workflows/black.yml'
      - '**.py'
jobs:
  Black:
    name: Check Black format
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install black
          python -m black -- . --check
