on:
  push:
    paths:
      - '.github/workflows/black.yml'
      - '**.py'
jobs:
  Black:
    name: Check Black format
    runs-on: [self-hosted, linux, x64, sudo]
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
