on:
  push:
    paths:
      - '.github/workflows/flutter-android.yml'
      - '**.gradle'
      - '**.kt'
      - '**.java'
      - '**.xml'
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: |
          if [ -d '../FedKit' ]; then
            pushd ../FedKit
            git fetch
            git reset --hard origin/main
            popd
          else
            git clone https://github.com/FedCampus/FedKit.git ../FedKit/
          fi
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fedcampus/
          flutter pub get
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Build APK
        run: |
          cd fedcampus/
          flutter build apk
