on:
  push:
    paths:
      - '.github/workflows/flutter.yml'
      - '**.dart'
      - '**pubspec.yaml'
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - run: git clone https://github.com/FedCampus/FedKit.git ../FedKit/
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          cd fedcampus/
          flutter pub get
      - name: Test
        run: |
          cd fedcampus/
          flutter test
      - name: Analysis
        run: |
          cd fedcampus/
          flutter analyze
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
